"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup


def get_data_files():
    resource_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'planEtGUI/data')
    file_types = ['.png', '.ini']
    datafiles = [('data', [os.path.join(root, f) for f in files for file_type in file_types if f.endswith(file_type)]) for root, dirs, files in os.walk(resource_path)]
    return datafiles

APP = ['planEtGUI/main.py']
DATA_FILES = get_data_files()
OPTIONS = {'argv_emulation': True,
           'iconfile': 'planEt_icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
